version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s,%(msecs)d %(name)s %(levelname)s %(process)d %(threadName)s %(funcName)s(): %(lineno)d %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  precise:
    format: '%(asctime)s,%(msecs)d %(name)s %(levelname)s %(process)d %(threadName)s %(funcName)s(): %(lineno)d %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    filename: log.log
    formatter: precise
    mode: a
    encoding: utf-8
loggers:
  consolelogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
